package FileGenerator.FilesContent;

public class ModelContent {

    public static String getModelContent() {
        return "package com.myCompany.ProjectName.Models;\n"
                + "\n"
                + "import com.fasterxml.jackson.annotation.JsonManagedReference;\n"
                + "import jakarta.persistence.Entity;\n"
                + "import org.antlr.v4.runtime.misc.NotNull;\n"
                + "import org.springframework.format.annotation.DateTimeFormat;\n"
                + "\n"
                + "import jakarta.persistence.*;\n"
                + "\n"
                + "import java.time.LocalDate;\n"
                + "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "\n"
                + "@Entity\n"
                + "public class Invoice {\n"
                + "    @Id\n"
                + "    @GeneratedValue(strategy = GenerationType.IDENTITY)\n"
                + "    private Long id;\n"
                + "    private String invoiceNumber;\n"
                + "    @DateTimeFormat(pattern = \"yyyy-MM-dd\")\n"
                + "    private LocalDate date;\n"
                + "    @NotNull\n"
                + "    private Float amount;\n"
                + "\n"
                + "    @OneToMany(mappedBy = \"invoice\", cascade = CascadeType.ALL, orphanRemoval = true)\n"
                + "    @JsonManagedReference\n"
                + "    private List<InvoiceItem> items = new ArrayList<>();\n"
                + "\n"
                + "    // getters and setters\n"
                + "\n"
                + "    public Invoice() {\n"
                + "    }\n"
                + "\n"
                + "    public Invoice(Long id, String invoiceNumber, LocalDate date, Float amount, List<InvoiceItem> items) {\n"
                + "        this.id = id;\n"
                + "        this.invoiceNumber = invoiceNumber;\n"
                + "        this.date = date;\n"
                + "        this.amount = amount;\n"
                + "        this.items = items;\n"
                + "    }\n"
                + "\n"
                + "    public Long getId() {\n"
                + "        return id;\n"
                + "    }\n"
                + "\n"
                + "    public void setId(Long id) {\n"
                + "        this.id = id;\n"
                + "    }\n"
                + "\n"
                + "    public String getInvoiceNumber() {\n"
                + "        return invoiceNumber;\n"
                + "    }\n"
                + "\n"
                + "    public void setInvoiceNumber(String invoiceNumber) {\n"
                + "        this.invoiceNumber = invoiceNumber;\n"
                + "    }\n"
                + "\n"
                + "    public LocalDate getDate() {\n"
                + "        return date;\n"
                + "    }\n"
                + "\n"
                + "    public void setDate(LocalDate date) {\n"
                + "        this.date = date;\n"
                + "    }\n"
                + "\n"
                + "    public Float getAmount() {\n"
                + "        return amount;\n"
                + "    }\n"
                + "\n"
                + "    public void setAmount(Float amount) {\n"
                + "        this.amount = amount;\n"
                + "    }\n"
                + "\n"
                + "    public List<InvoiceItem> getItems() {\n"
                + "        return items;\n"
                + "    }\n"
                + "\n"
                + "    public void setItems(List<InvoiceItem> items) {\n"
                + "        this.items = items;\n"
                + "    }\n"
                + "}\n";
    }


}
