package FileGenerator.FilesContent;

public class ServiceContent {

    public static String getServiceContent() {
        return "package com.myCompany.ProjectName.Service;\n"
                + "\n"
                + "import com.myCompany.ProjectName.Models.Invoice;\n"
                + "import com.myCompany.ProjectName.Models.InvoiceItem;\n"
                + "import com.myCompany.ProjectName.Repository.InvoiceItemRepository;\n"
                + "import com.myCompany.ProjectName.Repository.InvoiceRepository;\n"
                + "import org.springframework.beans.factory.annotation.*;\n"
                + "import org.springframework.stereotype.Service;;\n"
                + "\n"
                + "import java.util.List;\n"
                + "\n"
                + "@Service\n"
                + "public class InvoiceService {\n"
                + "    @Autowired\n"
                + "    private InvoiceRepository invoiceRepository;\n"
                + "\n"
                + "    @Autowired\n"
                + "    private InvoiceItemRepository invoiceItemRepository;\n"
                + "\n"
                + "    public List<Invoice> getAllInvoices() {\n"
                + "        return invoiceRepository.findAll();\n"
                + "    }\n"
                + "\n"
                + "    public Invoice getInvoiceById(Long id) {\n"
                + "        return invoiceRepository.findById(id).orElse(null);\n"
                + "    }\n"
                + "\n"
                + "    public Invoice addInvoice(Invoice invoice) {\n"
                + "        return invoiceRepository.save(invoice);\n"
                + "    }\n"
                + "\n"
                + "    public Invoice updateInvoice(Invoice updatedInvoice) {\n"
                + "        return invoiceRepository.save(updatedInvoice);\n"
                + "    }\n"
                + "\n"
                + "    public void deleteInvoice(Long id) {\n"
                + "        invoiceRepository.deleteById(id);\n"
                + "    }\n"
                + "\n"
                + "    public InvoiceItem getItemById(Long id) {\n"
                + "        return invoiceItemRepository.findById(id).orElse(null);\n"
                + "    }\n"
                + "}\n";
    }

}
